# Generated by Django 5.1.7 on 2025-03-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
